#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import division, print_function, absolute_import

__all__ = ["update_feeds", "send_emails"]

import sys
import time
from ugly import create_app
from ugly.models import User, Feed

# Set up the required DB context.
if "--config" in sys.argv:
    app = create_app(sys.argv[sys.argv.index("--config") + 1])
else:
    app = create_app()
app.test_request_context().push()


def update_feeds():
    for feed in Feed.query:
        feed.update()


def send_emails():
    for user in User.query:
        user.deliver_entries()


if __name__ == "__main__":
    while True:
        strt = time.time()

        print("Updating feeds...")
        update_feeds()
        print("... took {0} seconds".format(time.time() - strt))

        print("Sending emails...")
        send_emails()

        delta = 15. * 60 - time.time() + strt
        if delta > 0:
            print("Waiting...")
            time.sleep(delta)
